basePath: /api
definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.MerchantRegistrationDto:
    properties:
      accountHolderName:
        type: string
      merchantId:
        type: string
      merchantPassword:
        type: string
    type: object
  dto.PaymentRequestDto:
    properties:
      amount:
        type: number
      error_url:
        type: string
      failed_url:
        type: string
      merchant_id:
        type: string
      merchant_order_id:
        type: string
      merchant_password:
        type: string
      merchant_timestamp:
        type: string
      success_url:
        type: string
    required:
    - amount
    - error_url
    - failed_url
    - merchant_id
    - merchant_order_id
    - merchant_password
    - merchant_timestamp
    - success_url
    type: object
  models.Account:
    properties:
      balance:
        type: number
      bankIdentifierCode:
        type: string
      cardHolderName:
        type: string
      expirationDate:
        type: string
      id:
        type: string
      merchantAccount:
        type: boolean
      merchantId:
        type: string
      merchantPassword:
        type: string
      number:
        type: string
      primaryAccountNumber:
        type: string
      securityCode:
        type: string
    type: object
host: localhost:8443
info:
  contact: {}
  description: Microservice simulating bank accounts and cards
  title: Bank Service API
  version: "1.0"
paths:
  /account/register:
    post:
      consumes:
      - application/json
      description: Accepts merchant registration data
      parameters:
      - description: Merchant registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.MerchantRegistrationDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Register a new merchant
      tags:
      - accounts
  /payment/create/request:
    post:
      consumes:
      - application/json
      description: Accepts payment request data from acquirer
      parameters:
      - description: Payment request data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.PaymentRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create a new payment request
      tags:
      - payments
schemes:
- https
swagger: "2.0"
